name: 1. Tools A (Build & Attack)
on: [push]

jobs:
  build-and-compromise:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup & Build (Aplikasi Normal)
        run: |
          echo "print('[-] Memulai Aplikasi Utama...')" > app.py
          cat app.py > release_build.py

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0

      - name: Segel Integritas (Cosign Sign)
        env:
          COSIGN_PASSWORD: "unesa"
          COSIGN_YES: "true"
        run: |
          cosign generate-key-pair
          cosign sign-blob --yes --tlog-upload=false --key cosign.key release_build.py > release.sig

      # =========================================================
      # HAPUS BLOK INI JIKA INGIN PIPELINE AMAN (HIJAU)
      # BIARKAN BLOK INI JIKA INGIN PIPELINE DISERANG (MERAH)
      # =========================================================
      
      # Membungkus File, Segel, dan Kunci Publik untuk dikirim ke Ruangan B
      - name: Upload Paket ke Tools B
        uses: actions/upload-artifact@v4
        with:
          name: paket-aplikasi
          path: |
            release_build.py
            release.sig
            cosign.pub
